name: Build - Meson
on: 
  pull_request:
    branches:
      - "main"
  push:
jobs:
  build:
    name: Build and Comp Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Meson
      run: sudo apt-get update && sudo apt-get install clang-12  python3 python3-pip python3-setuptools python3-wheel ninja-build && pip3 install meson
    - name: Meson
      run: meson builddir
    - name: Ninja
      run: cd builddir && ninja
    - name: Build Example Normal
      run: cd builddir &&  ./peregrine.elf compile ../can_comp.pe -o output && ./peregrine.elf -js compile ../can_comp.js.pe -o output.js
    - name: Run Default
      run: cd builddir && ./output 
    - name: Run Release Default
      run: cd builddir && ./peregrine.elf compile ../can_comp.pe -o output -release && ./output 
    - name: Run JS
      run: cd builddir && node ./output.js
